services:
  neo4j:
    image: neo4j:5.20.0
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password1234
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    networks:
      - kg_network
    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://localhost:7474/ || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.4
    container_name: weaviate_db
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    # --- FINAL CORRECTED ENVIRONMENT SECTION ---
    # Removed all unnecessary single quotes from values
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    networks:
      - kg_network
    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - kg_network
    healthcheck:
      test: ["CMD-SHELL", "ollama list"]
      interval: 5s
      timeout: 10s
      retries: 5

  ingestion:
    build:
      context: ./ingestion_pipeline
    container_name: ingestion_service
    depends_on:
      neo4j:
        condition: service_healthy
      weaviate:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./ingestion_pipeline:/app
    networks:
      - kg_network
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password1234
      - WEAVIATE_URL=http://weaviate:8080
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATA_SOURCE_PATH=/app/data/source/initial_documents.json

  api:
    build:
      context: ./api
    container_name: api_service
    depends_on:
      neo4j:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - kg_network
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password1234
      - WEAVIATE_URL=http://weaviate:8080
      - EMBEDDING_MODEL_NAME=all-MiniLM-L6-v2

volumes:
  neo4j_data:
  weaviate_data:
  ollama_data:

networks:
  kg_network:
    driver: bridge